### ISSUE TITLE
支持线程池的metrics

### ISSUE THREAD

**Issue by arebya** [dubbo/metrics#10]
自定义线程池，需要关注的poolSize,activeThreads,queuedTasks,completedTasks这些指标支持吗？

**Comment by ralf0131** [comment]
嗯，是可以的，目前这块metrics没有提供，可以考虑提供。欢迎一起共建，提供一个metrics-threadpool模块？

**Comment by arebya** [comment]
https://github.com/dubbo/metrics/pull/12

**Comment by biyuhao** [comment]
it's been fixed with https://github.com/dubbo/metrics/commit/289178d781fb6b908dd8fc160260e50f61b41b16
