### ISSUE TITLE
参与共建社区

### ISSUE THREAD

**Issue by bianlz** [dubbo/metrics#29]
hi，有共建社区么？譬如钉钉、微信等地址。
看了下metrics，感觉目前metrics还是在脱离hsf阶段，好多diamond的东西还在上面。

**Comment by ralf0131** [comment]
暂时没有钉钉微信。你有哪方面的需求，可以直接在issue上讨论。
metrics已经完全脱离了。目前不依赖任何阿里内部的依赖。

**Comment by bianlz** [comment]
👌
